version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
